import type { DraftModel, RevisionModel, ApprovalEntryModel } from './editorial.model.js';

const NOW = Date.now();
const days = (count: number) => new Date(NOW - count * 24 * 60 * 60 * 1000).toISOString();

/**
 * eight seeded drafts covering every editorial status, so the library has a
 * meaningful queue, history and approval trail on first run.
 */
export const seedDrafts: DraftModel[] = [
  {
    id: 'seed-draft-1',
    contentType: 'post',
    title: 'איך מדברים עם ילדים על יום אחרי',
    payload: {
      excerpt: 'שיחה כנה עם ילדים אחרי אירוע מטלטל, בלי להבטיח הבטחות שאי אפשר לקיים.',
      body: 'ילדים קולטים הרבה יותר ממה שאנחנו חושבים. הם שומעים את הטון, רואים את הפנים, ומרגישים מתי משהו לא נאמר.',
    },
    domains: ['family', 'anxiety'],
    status: 'draft',
    authorId: 'user-writer-1',
    authorName: 'נועה בר־און',
    currentVersion: 2,
    createdAt: days(12),
    updatedAt: days(3),
  },
  {
    id: 'seed-draft-2',
    contentType: 'post',
    title: 'שגרה חדשה: להרכיב יום כשהכול השתנה',
    payload: {
      excerpt: 'מדריך מעשי לבניית שגרה יומית אחרי תקופה ארוכה של חוסר ודאות.',
      body: 'שגרה היא לא לוח זמנים. היא רצף של עוגנים קטנים שמאפשרים ליום להחזיק את עצמו.',
    },
    domains: ['routine'],
    status: 'in_review',
    authorId: 'user-writer-1',
    authorName: 'נועה בר־און',
    currentVersion: 4,
    createdAt: days(20),
    updatedAt: days(5),
    submittedAt: days(5),
  },
  {
    id: 'seed-draft-3',
    contentType: 'media-record',
    title: 'הקלטה: סדנת נשימה מודרכת',
    payload: {
      description: 'סדנה בת 25 דקות בהנחיית מטפלת CBT, מותאמת להתקפי חרדה.',
      mediaUrl: 'https://www.youtube.com/watch?v=inpok4MKVLM',
      mediaType: 'video',
    },
    domains: ['anxiety', 'body'],
    status: 'changes_requested',
    authorId: 'user-writer-2',
    authorName: 'יונתן שגב',
    currentVersion: 3,
    createdAt: days(25),
    updatedAt: days(8),
    submittedAt: days(10),
    lastReviewerId: 'user-moderator-1',
    lastReviewNote: 'אפשר להוסיף תיאור קצר של הסדנה ולציין את שם המנחה.',
  },
  {
    id: 'seed-draft-4',
    contentType: 'post',
    title: 'מה עוזר לי בלילות',
    payload: {
      excerpt: 'שישה דברים קטנים שעזרו לחברי הקהילה לעבור את שעות הלילה.',
      body: 'הלילה מאריך כל מחשבה. אלה שישה דברים שחברי הקהילה סיפרו שעוזרים להם.',
    },
    domains: ['sleep'],
    status: 'approved',
    authorId: 'user-writer-3',
    authorName: 'מיכל אדרי',
    currentVersion: 5,
    createdAt: days(30),
    updatedAt: days(2),
    submittedAt: days(6),
    lastReviewerId: 'user-moderator-1',
  },
  {
    id: 'seed-draft-5',
    contentType: 'post',
    title: 'לחזור לעבודה בלי להתנצל',
    payload: {
      excerpt: 'על החזרה למקום העבודה, ועל מה שמותר לבקש.',
      body: 'החזרה לעבודה היא לא חזרה לעצמך הישן. זו כניסה למקום מוכר עם גוף אחר.',
    },
    domains: ['work'],
    status: 'published',
    contentRef: 'post-88',
    authorId: 'user-writer-1',
    authorName: 'נועה בר־און',
    currentVersion: 6,
    createdAt: days(60),
    updatedAt: days(30),
    submittedAt: days(40),
    publishedAt: days(30),
    lastReviewerId: 'user-moderator-1',
  },
  {
    id: 'seed-draft-6',
    contentType: 'media-record',
    title: 'פודקאסט: להתמודד יחד',
    payload: {
      description: 'שיחה עם שלושה חברי קהילה על מה שעזר להם בשנה הראשונה.',
      mediaUrl: 'https://www.youtube.com/watch?v=ZToicYcHIOU',
      mediaType: 'audio',
    },
    domains: ['community'],
    status: 'in_review',
    authorId: 'user-writer-2',
    authorName: 'יונתן שגב',
    currentVersion: 1,
    createdAt: days(4),
    updatedAt: days(1),
    submittedAt: days(1),
  },
  {
    id: 'seed-draft-7',
    contentType: 'post',
    title: 'כשהגוף זוכר לפני הראש',
    payload: {
      excerpt: 'על תגובות גופניות שמגיעות בלי אזהרה, ומה אפשר לעשות ברגע עצמו.',
      body: 'הגוף מגיב מהר מהמחשבה. זה לא כישלון — זו מערכת שעושה את עבודתה.',
    },
    domains: ['body', 'anxiety'],
    status: 'in_review',
    authorId: 'user-writer-3',
    authorName: 'מיכל אדרי',
    currentVersion: 2,
    createdAt: days(18),
    updatedAt: days(11),
    submittedAt: days(11),
  },
  {
    id: 'seed-draft-8',
    contentType: 'post',
    title: 'המדריך שלא הצליח להיכתב',
    payload: { excerpt: 'טיוטה שנשארה פתוחה.', body: '' },
    domains: [],
    status: 'archived',
    authorId: 'user-writer-2',
    authorName: 'יונתן שגב',
    currentVersion: 1,
    createdAt: days(90),
    updatedAt: days(75),
  },
];

/**
 * the version history behind the seeded drafts.
 */
export const seedRevisions: RevisionModel[] = [
  {
    id: 'seed-rev-1',
    draftId: 'seed-draft-1',
    versionNumber: 1,
    title: 'איך מדברים עם ילדים',
    payload: { excerpt: 'טיוטה ראשונה.', body: '' },
    domains: ['family'],
    authorId: 'user-writer-1',
    authorName: 'נועה בר־און',
    changeSummary: 'נוצרה טיוטה',
    createdAt: days(12),
  },
  {
    id: 'seed-rev-2',
    draftId: 'seed-draft-1',
    versionNumber: 2,
    title: 'איך מדברים עם ילדים על יום אחרי',
    payload: {
      excerpt: 'שיחה כנה עם ילדים אחרי אירוע מטלטל, בלי להבטיח הבטחות שאי אפשר לקיים.',
      body: 'ילדים קולטים הרבה יותר ממה שאנחנו חושבים.',
    },
    domains: ['family', 'anxiety'],
    authorId: 'user-writer-1',
    authorName: 'נועה בר־און',
    changeSummary: 'חודדה הכותרת ונוסף גוף ראשוני',
    createdAt: days(3),
  },
  {
    id: 'seed-rev-3',
    draftId: 'seed-draft-3',
    versionNumber: 3,
    title: 'הקלטה: סדנת נשימה מודרכת',
    payload: {
      description: 'סדנה בת 25 דקות בהנחיית מטפלת CBT.',
      mediaUrl: 'https://www.youtube.com/watch?v=inpok4MKVLM',
      mediaType: 'video',
    },
    domains: ['anxiety', 'body'],
    authorId: 'user-writer-2',
    authorName: 'יונתן שגב',
    changeSummary: 'נוסף תיאור הסדנה',
    createdAt: days(8),
  },
];

/**
 * the approval trail of the seeded drafts — a full editorial story for the
 * drafts that already went through review.
 */
export const seedApprovals: ApprovalEntryModel[] = [
  {
    id: 'seed-app-1',
    draftId: 'seed-draft-3',
    action: 'created',
    actorId: 'user-writer-2',
    actorName: 'יונתן שגב',
    actorRole: 'writer',
    toStatus: 'draft',
    versionNumber: 1,
    createdAt: days(25),
  },
  {
    id: 'seed-app-2',
    draftId: 'seed-draft-3',
    action: 'submitted',
    actorId: 'user-writer-2',
    actorName: 'יונתן שגב',
    actorRole: 'writer',
    fromStatus: 'draft',
    toStatus: 'in_review',
    versionNumber: 3,
    createdAt: days(10),
  },
  {
    id: 'seed-app-3',
    draftId: 'seed-draft-3',
    action: 'changes_requested',
    actorId: 'user-moderator-1',
    actorName: 'תמר לוי',
    actorRole: 'moderator',
    note: 'אפשר להוסיף תיאור קצר של הסדנה ולציין את שם המנחה.',
    fromStatus: 'in_review',
    toStatus: 'changes_requested',
    versionNumber: 3,
    createdAt: days(8),
  },
  {
    id: 'seed-app-4',
    draftId: 'seed-draft-4',
    action: 'submitted',
    actorId: 'user-writer-3',
    actorName: 'מיכל אדרי',
    actorRole: 'writer',
    fromStatus: 'draft',
    toStatus: 'in_review',
    versionNumber: 5,
    createdAt: days(6),
  },
  {
    id: 'seed-app-5',
    draftId: 'seed-draft-4',
    action: 'approved',
    actorId: 'user-moderator-1',
    actorName: 'תמר לוי',
    actorRole: 'moderator',
    note: 'מוכן לפרסום. תודה על העבודה היסודית.',
    fromStatus: 'in_review',
    toStatus: 'approved',
    versionNumber: 5,
    createdAt: days(2),
  },
  {
    id: 'seed-app-6',
    draftId: 'seed-draft-5',
    action: 'approved',
    actorId: 'user-moderator-1',
    actorName: 'תמר לוי',
    actorRole: 'moderator',
    fromStatus: 'in_review',
    toStatus: 'approved',
    versionNumber: 6,
    createdAt: days(32),
  },
  {
    id: 'seed-app-7',
    draftId: 'seed-draft-5',
    action: 'published',
    actorId: 'user-admin-1',
    actorName: 'אורי מזרחי',
    actorRole: 'admin',
    fromStatus: 'approved',
    toStatus: 'published',
    versionNumber: 6,
    createdAt: days(30),
  },
];
