import { App } from './app.js';
import type { PlainApp } from './app.js';

const shot = (seed: string) => `https://images.unsplash.com/${seed}?auto=format&fit=crop&w=900&q=80`;

/**
 * create a single mock App, optionally overriding any of its properties.
 */
export function mockApp(overrides: Partial<PlainApp> = {}): App {
  return App.from({
    id: 'breathe-calm',
    slug: 'breathe-calm',
    name: 'נשימה רגועה',
    subtitle: 'תרגילי נשימה מודרכים להרגעה מיידית',
    fullDescription:
      'אפליקציה שמלווה אותך בתרגילי נשימה קצרים ברגעים של הצפה. מגוון קצבים, ליווי קולי רגוע, ותזכורות עדינות לאורך היום. מתאימה במיוחד לרגעי חרדה, טריגרים והרגעה לפני שינה.',
    externalLink: 'https://example.com/breathe',
    icon: '🫧',
    screenshots: [
      shot('photo-1506126613408-eca07ce68773'),
      shot('photo-1499209974431-9dddcece7f88'),
      shot('photo-1518495973542-4542c06a5843'),
    ],
    costType: 'חינם לחברי הקהילה',
    platform: ['iOS', 'Android'],
    language: 'עברית',
    requiresSignup: false,
    clickCount: 1240,
    helpfulYes: 312,
    helpfulNo: 28,
    isFeatured: true,
    developerName: 'דנה לוי',
    originatorName: 'יוסי כהן',
    domains: ['מיינדפולנס ונשימות', 'חרדה', 'שינה'],
    avgRating: 4.7,
    ratingCount: 96,
    ratingHistogram: [2, 3, 6, 20, 65],
    status: 'approved',
    ...overrides,
  });
}

/**
 * the seed catalog of published coping apps, ported from the Helam Club
 * marketplace prototype.
 */
export function mockApps(): App[] {
  return [
    mockApp(),
    mockApp({
      id: 'sleep-anchor',
      slug: 'sleep-anchor',
      name: 'עוגן לילה',
      subtitle: 'סיפורי הרדמה ונופי סאונד לשינה עמוקה',
      fullDescription:
        'ספרייה של נופי סאונד וסיפורי הרדמה בעברית, שנבנתה מתוך הצורך של מתמודדים עם הפרעות שינה. טיימר שקיעה, מצב לילה כהה, ואפשרות להורדה לשימוש ללא אינטרנט.',
      externalLink: 'https://example.com/sleep',
      icon: '🌙',
      screenshots: [shot('photo-1520206183501-b80df61043c2'), shot('photo-1444703686981-a3abbc4d4fe3')],
      costType: 'כולל רכישות',
      platform: ['iOS', 'Android', 'Web'],
      requiresSignup: true,
      clickCount: 870,
      helpfulYes: 190,
      helpfulNo: 41,
      isFeatured: false,
      developerName: 'אורי מזרחי',
      originatorName: undefined,
      domains: ['שינה', 'מיינדפולנס ונשימות', 'חרדה'],
      avgRating: 4.3,
      ratingCount: 58,
      ratingHistogram: [1, 4, 8, 18, 27],
    }),
    mockApp({
      id: 'ground-me',
      slug: 'ground-me',
      name: 'קרקוע',
      subtitle: 'כלים להתמודדות עם טריגרים ופלאשבקים',
      fullDescription:
        'ערכת כלי קרקוע (grounding) זמינים בלחיצה אחת ברגע של הצפה או פלאשבק — תרגילי 5-4-3-2-1, אובייקטים מרגיעים, ואנשי קשר לשעת חירום. עוצבה יחד עם מתמודדי פוסט-טראומה.',
      externalLink: 'https://example.com/ground',
      icon: '🪨',
      screenshots: [shot('photo-1476611317561-60117649dd94'), shot('photo-1500534623283-312aade485b7')],
      costType: 'חינם לחברי הקהילה',
      platform: ['iOS', 'Android'],
      requiresSignup: false,
      clickCount: 1520,
      helpfulYes: 402,
      helpfulNo: 19,
      isFeatured: true,
      developerName: 'מיכל ברק',
      originatorName: 'שרה דוד',
      domains: ['טריגרים', 'ויסות רגשי', 'חרדה'],
      avgRating: 4.9,
      ratingCount: 143,
      ratingHistogram: [1, 1, 4, 15, 122],
    }),
    mockApp({
      id: 'mood-map',
      slug: 'mood-map',
      name: 'מצב רוח',
      subtitle: 'יומן רגשי פשוט למעקב וויסות',
      fullDescription:
        'יומן רגשי יומי שעוזר לזהות דפוסים, טריגרים והתקדמות. גרפים ברורים, תזכורות עדינות, וייצוא לשיתוף עם מטפל. בלי לחץ, בלי שיפוטיות.',
      externalLink: 'https://example.com/mood',
      icon: '📓',
      screenshots: [shot('photo-1517842645767-c639042777db'), shot('photo-1522202176988-66273c2fd55f')],
      costType: 'חינם לחברי הקהילה',
      platform: ['Web', 'iOS'],
      requiresSignup: false,
      clickCount: 640,
      helpfulYes: 121,
      helpfulNo: 33,
      isFeatured: false,
      developerName: 'תמר גל',
      originatorName: undefined,
      domains: ['ויסות רגשי', 'דיכאון ותחושת תקיעות', 'אשמה, בושה וביקורת עצמית'],
      avgRating: 4.1,
      ratingCount: 47,
      ratingHistogram: [2, 3, 9, 15, 18],
    }),
    mockApp({
      id: 'connect-circle',
      slug: 'connect-circle',
      name: 'מעגל',
      subtitle: 'קבוצות תמיכה קטנות ומוגנות',
      fullDescription:
        'מרחב מוגן למפגשים קבוצתיים קטנים בין מתמודדים ובני משפחה, עם מנחה. נבנה כדי להילחם בבדידות וליצור חיבור אמיתי בקצב שלך.',
      externalLink: 'https://example.com/circle',
      icon: '🤝',
      screenshots: [shot('photo-1529156069898-49953e39b3ac'), shot('photo-1543269865-cbf427effbad')],
      costType: 'חינם לחברי הקהילה',
      platform: ['Web'],
      requiresSignup: true,
      clickCount: 410,
      helpfulYes: 88,
      helpfulNo: 12,
      isFeatured: false,
      developerName: 'נועם פרץ',
      originatorName: 'רון אבני',
      domains: ['בדידות וחיבור חברתי', 'משפחה, זוגיות ויחסים', 'דיכאון ותחושת תקיעות'],
      avgRating: 4.5,
      ratingCount: 34,
      ratingHistogram: [1, 1, 3, 10, 19],
    }),
    mockApp({
      id: 'focus-work',
      slug: 'focus-work',
      name: 'מיקוד',
      subtitle: 'ניהול משימות עדין לימים קשים',
      fullDescription:
        'מנהל משימות שמבין שיש ימים קשים. מפרק משימות לצעדים זעירים, חוגג ניצחונות קטנים, ומאפשר לדחות בלי אשמה. תוכנן לחזרה עדינה לעבודה וללימודים.',
      externalLink: 'https://example.com/focus',
      icon: '🎯',
      screenshots: [shot('photo-1484480974693-6ca0a78fb36b'), shot('photo-1499750310107-5fef28a66643')],
      costType: 'כולל רכישות',
      platform: ['iOS', 'Android', 'Web'],
      requiresSignup: false,
      clickCount: 720,
      helpfulYes: 143,
      helpfulNo: 37,
      isFeatured: false,
      developerName: 'עידן שמש',
      originatorName: undefined,
      domains: ['עבודה וקריירה', 'לימודים ואקדמיה', 'ויסות רגשי'],
      avgRating: 4.2,
      ratingCount: 51,
      ratingHistogram: [2, 3, 8, 19, 19],
    }),
  ];
}
