import type { TaggedContent } from './domain-types.js';

const CALM_ABSTRACT =
  'https://storage.googleapis.com/bit-generated-images/images/image_a_calm__serene_abstract_illust_0_1785226622893.png';
const COMMUNITY_CIRCLE =
  'https://storage.googleapis.com/bit-generated-images/images/image_a_warm_supportive_community_ga_0_1785226615007.png';

/**
 * the cross-sliced ecosystem content, tagged with knowledge-domain ids
 * (slugs). seeded on start so the domains-lobby and community-wisdom
 * surfaces can slice real content by domain. content spans every channel:
 * knowledge records, blog posts, events, gallery items and toolbox apps.
 */
export const CONTENT_MOCKS: TaggedContent[] = [
  {
    type: `record`,
    id: `grounding-flashbacks`,
    title: `קרקוע ברגע של פלאשבק`,
    excerpt: `תרגיל מודרך קצר להחזרת תחושת הביטחון בזמן הצפה או פלאשבק.`,
    url: `/knowledge/grounding-flashbacks`,
    imageUrl: CALM_ABSTRACT,
    domains: [`triggers`, `anxiety`, `emotional-regulation`],
  },
  {
    type: `record`,
    id: `panic-breathing`,
    title: `נשימה בזמן התקף חרדה`,
    excerpt: `הקלטה קולית שמלווה אותך צעד-צעד דרך התקף חרדה.`,
    url: `/knowledge/panic-breathing`,
    imageUrl: CALM_ABSTRACT,
    domains: [`anxiety`, `mindfulness-breathing`],
  },
  {
    type: `record`,
    id: `life-after-panel`,
    title: `החיים שאחרי — שולחן עגול`,
    excerpt: `שיחה כנה של ארבעה מתמודדים על השגרה, הזוגיות והתקווה שאחרי.`,
    url: `/knowledge/life-after-panel`,
    imageUrl: COMMUNITY_CIRCLE,
    domains: [`family-relationships`, `depression-stuckness`],
  },
  {
    type: `record`,
    id: `understanding-ptsd`,
    title: `מה זה בעצם פוסט-טראומה?`,
    excerpt: `הסבר מקצועי ונגיש על מנגנוני הטראומה בגוף ובנפש.`,
    url: `/knowledge/understanding-ptsd`,
    imageUrl: CALM_ABSTRACT,
    domains: [`emotional-regulation`],
  },
  {
    type: `record`,
    id: `choosing-therapy`,
    title: `איך בוחרים טיפול שמתאים לי?`,
    excerpt: `סקירה של הגישות המרכזיות ושאלות שכדאי לשאול מטפל.`,
    url: `/knowledge/choosing-therapy`,
    imageUrl: CALM_ABSTRACT,
    domains: [`medication-psychiatry`, `depression-stuckness`],
  },
  {
    type: `record`,
    id: `rights-guide`,
    title: `מדריך מיצוי זכויות למתמודדים`,
    excerpt: `כל מה שצריך לדעת על הזכויות שלך מול הרשויות והביטוח.`,
    url: `/knowledge/rights-guide`,
    imageUrl: COMMUNITY_CIRCLE,
    domains: [`rights`, `work-career`],
  },
  {
    type: `post`,
    id: `shame-and-guilt`,
    title: `הבושה שאף אחד לא מדבר עליה`,
    excerpt: `על אשמה ובושה אחרי טראומה — למה הן מופיעות, ואיך אפשר להתחיל לשחרר.`,
    url: `/blog/shame-and-guilt`,
    imageUrl: CALM_ABSTRACT,
    domains: [`guilt-shame`, `emotional-regulation`],
  },
  {
    type: `post`,
    id: `couples-after-trauma`,
    title: `זוגיות בצל הפוסט-טראומה`,
    excerpt: `שיתוף אישי על מערכת יחסים שמחזיקה שניים — כשאחד המתמודד.`,
    url: `/blog/couples-after-trauma`,
    imageUrl: COMMUNITY_CIRCLE,
    domains: [`family-relationships`, `loneliness-connection`],
  },
  {
    type: `post`,
    id: `triggers-toolkit`,
    title: `5 כלים שעוזרים לי עם טריגרים`,
    excerpt: `רשימה פרקטית של כלים קטנים שאני משתמש בהם ברגעים של הצפה.`,
    url: `/blog/triggers-toolkit`,
    imageUrl: CALM_ABSTRACT,
    domains: [`triggers`, `mindfulness-breathing`, `anxiety`],
  },
  {
    type: `post`,
    id: `sleep-story`,
    title: `הלילות הארוכים — ומה שעזר לי לישון`,
    excerpt: `על נדודי שינה אחרי טראומה, וסיפור אישי על הדרך חזרה למנוחה.`,
    url: `/blog/sleep-story`,
    imageUrl: CALM_ABSTRACT,
    domains: [`sleep`, `anxiety`],
  },
  {
    type: `event`,
    id: `round-table-shame`,
    title: `שולחן עגול: בושה ואשמה`,
    excerpt: `מפגש פתוח בהנחיית אנשי מקצוע ומתמודדים סביב נושא הבושה.`,
    url: `/events/round-table-shame`,
    imageUrl: COMMUNITY_CIRCLE,
    domains: [`guilt-shame`, `emotional-regulation`],
  },
  {
    type: `event`,
    id: `webinar-sleep`,
    title: `וובינר: שינה וטראומה`,
    excerpt: `הרצאה מקצועית על הקשר בין פוסט-טראומה להפרעות שינה + שאלות.`,
    url: `/events/webinar-sleep`,
    imageUrl: CALM_ABSTRACT,
    domains: [`sleep`, `anxiety`],
  },
  {
    type: `event`,
    id: `local-tlv`,
    title: `מפגש קהילה — תל אביב`,
    excerpt: `מפגש פנים אל פנים לחברי הקהילה באזור המרכז, באווירה רגועה.`,
    url: `/events/local-tlv`,
    imageUrl: COMMUNITY_CIRCLE,
    domains: [`loneliness-connection`],
  },
  {
    type: `app`,
    id: `app-inner-voice`,
    title: `הקול הפנימי — יומן מחשבות`,
    excerpt: `אפליקציה לזיהוי ותרגום מחשבות ביקורתיות למשפטים תומכים.`,
    url: `/toolbox/app-inner-voice`,
    domains: [`guilt-shame`, `depression-stuckness`],
  },
  {
    type: `app`,
    id: `app-breathe`,
    title: `נשימה — מדריך נשימות אינטראקטיבי`,
    excerpt: `תרגילי נשימה מודרכים להרגעת הגוף ברגעי חרדה והצפה.`,
    url: `/toolbox/app-breathe`,
    domains: [`mindfulness-breathing`, `anxiety`, `triggers`],
  },
  {
    type: `gallery`,
    id: `g1`,
    title: `שקט אחרי הסערה`,
    excerpt: `יצירה מהגלריה הקהילתית בהשראת תחושת רוגע וויסות.`,
    url: `/gallery/g1`,
    imageUrl: CALM_ABSTRACT,
    domains: [`emotional-regulation`],
  },
  {
    type: `gallery`,
    id: `g3`,
    title: `נשימה`,
    excerpt: `יצירה מהגלריה הקהילתית בהשראת מיינדפולנס ורוגע.`,
    url: `/gallery/g3`,
    imageUrl: CALM_ABSTRACT,
    domains: [`mindfulness-breathing`, `anxiety`],
  },
  {
    type: `gallery`,
    id: `g7`,
    title: `בוקר חדש`,
    excerpt: `יצירה מהגלריה הקהילתית בהשראת תחושת שחרור מהעבר.`,
    url: `/gallery/g7`,
    imageUrl: CALM_ABSTRACT,
    domains: [`guilt-shame`],
  },
];
