import type { AdminMemberProfile } from './use-member-approvals.js';

/**
 * invented member applications covering every membership state, used for
 * compositions and tests. these are not real people — nothing here is ever
 * seeded into a database (see the note in membership.node.runtime.ts).
 */
export const MOCK_MEMBER_PROFILES: AdminMemberProfile[] = [
  {
    userId: `user-1`,
    status: `pending`,
    accountEmail: `rotem@example.com`,
    accountDisplayName: `rotem`,
    provider: `google`,
    fullName: `רותם לוי`,
    phone: `050-1234567`,
    contactEmail: `rotem@example.com`,
    age: 34,
    city: `תל אביב`,
    communityRoles: `מנחה מעגלים`,
    gender: `female`,
    injuryNote: `פציעת ברך מהשירות, בשיקום כשנתיים`,
    recognitionStatus: `recognized`,
    welcomeCallsOptIn: true,
    interests: [`תעסוקה`, `ספורט`],
    submittedAt: `2026-08-01T09:00:00.000Z`,
    decisionNote: ``,
    createdAt: `2026-08-01T08:55:00.000Z`,
  },
  {
    userId: `user-2`,
    status: `pending`,
    accountEmail: `amir@example.com`,
    accountDisplayName: `amir`,
    provider: `email`,
    fullName: `אמיר כהן`,
    phone: `052-7654321`,
    contactEmail: `amir.work@example.com`,
    age: 41,
    city: `חיפה`,
    communityRoles: ``,
    gender: `male`,
    injuryNote: `פגיעת ראש, מתמודד עם עומס חושי`,
    recognitionStatus: `in-process`,
    welcomeCallsOptIn: false,
    interests: [`בריאות הנפש`],
    submittedAt: `2026-08-02T14:20:00.000Z`,
    decisionNote: ``,
    createdAt: `2026-08-02T14:10:00.000Z`,
  },
  {
    userId: `user-3`,
    status: `approved`,
    accountEmail: `yael@example.com`,
    accountDisplayName: `יעל`,
    provider: `google`,
    fullName: `יעל ברק`,
    phone: `054-1112233`,
    contactEmail: `yael@example.com`,
    age: 29,
    city: `ירושלים`,
    communityRoles: `מלווה שיחות וולקאם`,
    gender: `female`,
    injuryNote: `פציעת גב`,
    recognitionStatus: `planned`,
    welcomeCallsOptIn: true,
    interests: [`זוגיות`, `תעסוקה`],
    submittedAt: `2026-07-20T10:00:00.000Z`,
    decidedAt: `2026-07-21T08:00:00.000Z`,
    decisionNote: `הכרנו מהאקתון 1`,
    createdAt: `2026-07-20T09:50:00.000Z`,
  },
  {
    userId: `user-4`,
    status: `none`,
    accountEmail: `newcomer@example.com`,
    accountDisplayName: `newcomer`,
    provider: `email`,
    fullName: ``,
    phone: ``,
    contactEmail: ``,
    age: 0,
    city: ``,
    communityRoles: ``,
    gender: ``,
    injuryNote: ``,
    recognitionStatus: ``,
    welcomeCallsOptIn: false,
    interests: [],
    decisionNote: ``,
    createdAt: `2026-08-05T18:00:00.000Z`,
  },
];
